# 2025 official MC is reused from Run3_2024 (reuse_mc_from_era).
custom_CI:
  sampleType: HH
  crossSection: 1pb
  generator: powheg
  fs_nanoAOD: T3_CH_CERNBOX:/store/user/vdamante/
  dirName: "nanobbtt_2024"
