analysis: hh_bbww
type: resonant
model:
  parameters: [ MX ]
  param_dependent_bkg: true
  input_file_pattern: ${ERA}/DNN_m${MX}_vs_HME/DNN_m${MX}_vs_HME.root
signalFractionForRelevantBins: 0.2
eras:
  - Run3_2022
  - Run3_2022EE
  - Run3_2023
  - Run3_2023BPix
channels:
  - muMu
  - eMu
  - eE
categories:
  - OS_Iso/res2b
  - OS_Iso/recovery
processes:
  - process: data_obs
    is_data: true
    is_asimov_data: true
  - process: XtoHHto2B2W_2L_${MX} # GluGluToRadion2L_${MX}
    hist_name: XtoHHto2B2W_2L_${MX} # GluGluToRadion2L_${MX}
    param_values: [ 300 ]
    is_signal: true
  - custom_CI_Background
uncertainties:
  - name: lumi_13p6TeV
    type: lnN
    value: 0.014 # https://twiki.cern.ch/twiki/bin/view/CMS/LumiRecommendationsRun3


  - name: CMS_eff_m_id
    type: shape
  - name: CMS_eff_m_id_iso
    type: shape
  - name: EleID_TightIDIso
    type: shape

  - name: SingleEleTrg
    type: shape
  - name: SingleMuonTrg
    type: shape

  - name: CMS_pileup
    type: shape

  - name: CMS_scale_j
    type: shape
  - name: CMS_res_j
    type: shape
  - name: CMS_scale_e
    type: shape


autolnNThr: 0.1
asymlnNThr: 0.001
ignorelnNThr: 0.001
autoMCStats:
  apply: true
  threshold: 20
  apply_to_signal: true
  mode: 1
