fs_default:
  - /builds/cms-flaf/flaf_integration/output/HH_bbWW

analysis_config_area: config
compute_unc_variations: true
compute_unc_histograms: true
store_noncentral: true
phys_model: TestModel

QCDRegions:
  - OS_Iso

StatInference:
  config: config/Datacards/CI_card.yaml
  hist_bins: config/Datacards/CI_binning.json
  param_values: [ 300 ]

# Do not remove DNN variables, they are needed for the datacard creation.
variables:
  - lep1_pt
  - DeepHME_mass
  - DNN_M300_Signal
  - DNN_M300_TT

  - name: lep1_pt_vs_eta
    vars: [ lep1_pt, lep1_eta ]
    plot_task: False

  - name: DNN_m300_vs_HME
    vars: [ DNN_M300_Signal, DeepHME_mass ]
