.DY_processors: &DY_processors
  - name: Stitcher
    module: FLAF.Processors.MCStitching
    class: MCStitcher
    config: FLAF/config/Processors/stitching_DY_amcatnlo_Vpt_NpNLO.yaml
    # A stitcher writes its denominator into the anaCache at AnaTuple and has to be present
    # at AnaTupleMerge to combine it again; only these two stages are ever looked up.
    stages: [ AnaTuple, AnaTupleMerge ]
    dependency_level:
      AnaTuple: file
      AnaTupleMerge: process

.DY_processors_allFlavors: &DY_processors_allFlavors
  - name: Stitcher
    module: FLAF.Processors.MCStitching
    class: MCStitcher
    config: FLAF/config/Processors/stitching_DY_amcatnlo_Vpt_NpNLO_allFlavors.yaml
    stages: [ AnaTuple, AnaTupleMerge ]
    verbose: 1
    dependency_level:
      AnaTuple: file
      AnaTupleMerge: process

.TT_processors: &TT_processors
  - name: Stitcher
    module: FLAF.Processors.MCStitchingTT
    class: TTStitcher
    config: FLAF/config/Processors/stitching_TT_decayMode.yaml
    stages: [ AnaTuple, AnaTupleMerge ]

.W_processors_allFlavors: &W_processors_allFlavors
  - name: Stitcher
    module: FLAF.Processors.MCStitching
    class: MCStitcher
    config: FLAF/config/Processors/stitching_W_amcatnlo_Vpt_NpNLO.yaml
    stages: [ AnaTuple, AnaTupleMerge ]
    verbose: 1
    dependency_level:
      AnaTuple: file
      AnaTupleMerge: process
