UseParametric: true
apply_common_gradients: true
batch_compression_factor: 10
nClasses: 2
disco_activation: tanh
disco_lambda_factor: 0
dropout: 0.0
features:
  - lep1_pt
  - lep1_phi
  - lep1_eta
  - lep1_mass
  - lep2_pt
  - lep2_phi
  - lep2_eta
  - lep2_mass
  - met_pt
  - met_phi
highlevelfeatures:
  - HT
  - dR_dilep
  - dR_dibjet
  - dR_dilep_dibjet
  - dR_dilep_dijet
  - dPhi_lep1_lep2
  - dPhi_jet1_jet2
  - dPhi_MET_dilep
  - dPhi_MET_dibjet
  - MT
  - MT2_ll
  - MT2_bb
  - MT2_blbl
  - ll_mass
  - CosTheta_bb
hmefeatures: [ ]
input_folder: /eos/user/d/daebi/DNN_Training_Datasets/DoubleLepton_v3/Dataset_Run3_2022/
learning_rate: 0.001
listfeatures:
  - - - centralJet_pt
      - centralJet_phi
      - centralJet_eta
      - centralJet_mass
      - centralJet_btagPNetB
    - 0
  - - - centralJet_pt
      - centralJet_phi
      - centralJet_eta
      - centralJet_mass
      - centralJet_btagPNetB
    - 1
  - - - centralJet_pt
      - centralJet_phi
      - centralJet_eta
      - centralJet_mass
      - centralJet_btagPNetB
    - 2
  - - - centralJet_pt
      - centralJet_phi
      - centralJet_eta
      - centralJet_mass
      - centralJet_btagPNetB
    - 3
  - - - SelectedFatJet_pt
      - SelectedFatJet_phi
      - SelectedFatJet_eta
      - SelectedFatJet_mass
      - SelectedFatJet_particleNetWithMass_HbbvsQCD
      - SelectedFatJet_SubJet1_btagDeepB
      - SelectedFatJet_SubJet1_eta
      - SelectedFatJet_SubJet1_mass
      - SelectedFatJet_SubJet1_phi
      - SelectedFatJet_SubJet1_pt
      - SelectedFatJet_SubJet2_btagDeepB
      - SelectedFatJet_SubJet2_eta
      - SelectedFatJet_SubJet2_mass
      - SelectedFatJet_SubJet2_phi
      - SelectedFatJet_SubJet2_pt
    - 0
n_disco_layers: 5
n_disco_units: 512
n_epochs: 40
parametric_list:
  - 600
patience: 100
use_batch_norm: false
weight_decay: 0.004
