UseParametric: true
nClasses: 2
activation: tanh
batch_size: 10000
dropout: 0.3
features:
  - lep1_pt
  - lep1_phi
  - lep1_eta
  - lep1_mass
  - lep2_pt
  - lep2_phi
  - lep2_eta
  - lep2_mass
  - PuppiMET_pt
  - PuppiMET_phi
  - HT
  - dR_dilep
  - dR_dibjet
  - dR_dilep_dibjet
  - dR_dilep_dijet
  - dPhi_lep1_lep2
  - dPhi_jet1_jet2
  - dPhi_MET_dilep
  - dPhi_MET_dibjet
  - MT
  - MT2_ll
  - MT2_bb
  - MT2_blbl
  - ll_mass
  - CosTheta_bb
  - bjet1_pt
  - bjet1_phi
  - bjet1_eta
  - bjet1_mass
  - bjet1_btagPNetB
  - bjet2_pt
  - bjet2_phi
  - bjet2_eta
  - bjet2_mass
  - bjet2_btagPNetB
  - wjet1_pt
  - wjet1_phi
  - wjet1_eta
  - wjet1_mass
  - wjet1_btagPNetB
  - wjet2_pt
  - wjet2_phi
  - wjet2_eta
  - wjet2_mass
  - wjet2_btagPNetB
  # - fatbjet_pt
  # - fatbjet_phi
  # - fatbjet_eta
  # - fatbjet_mass
  # - fatbjet_particleNetWithMass_HbbvsQCD
learning_rate: 0.0001
n_layers: 5
n_units: 512
n_epochs: 500
parametric_list:
  - 250
  - 260
  - 270
  - 280
  - 300
  - 350
  - 450
  - 550
  - 600
  - 650
  - 700
  - 800
  - 1000
  - 1200
  - 1400
  - 1600
  - 1800
  - 2000
  - 2500
  - 3000
  - 4000
  - 5000
patience: 100
use_batch_norm: true
weight_decay: 0.004
